import { type NextPage } from "next";
import Head from "next/head";
import { Odontogram } from "~/components/Odontogram";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-[#E0F2F8]">
				<h1>hola</h1>
				<Odontogram />
			</main>
		</>
	);
};

export default Home;
